# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.SourceVersion)'
  dockerRepository: bratislava/$(Build.Repository.Name)/$(Build.Repository.Name)

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ghcr'
        repository: $(dockerRepository)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
      displayName: Build Docker Image
    - task: Docker@2
      inputs:
        containerRegistry: 'ghcr'
        repository: $(dockerRepository)
        command: 'Push'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual')))
      displayName: Push Docker Image (not on PR)

- stage: Dev
  dependsOn:
    - Build
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual')))
  variables:
    BE_HOSTNAME: api.kupaliska.dev.bratislava.sk
  jobs:
    - template: ./kubernetes/release-template.yml
      parameters:
        environment: 'Dev.bratislava-monorepo'
        hostname: kupaliska.dev.bratislava.sk

- stage: Staging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
    - Dev
  variables:
    BE_HOSTNAME: api.kupaliska.staging.bratislava.sk
  jobs:
    - template: ./kubernetes/release-template.yml
      parameters:
        environment: 'Staging.bratislava-monorepo'
        hostname: kupaliska.staging.bratislava.sk

- stage: Production
  dependsOn:
    - Staging
  variables:
    BE_HOSTNAME: api.kupaliska.bratislava.sk
  jobs:
    - template: ./kubernetes/release-template.yml
      parameters:
        environment: 'Prod.bratislava-monorepo'
        hostname: kupaliska.bratislava.sk