# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.SourceVersion)'
  dockerRepository: bratislava/$(Build.Repository.Name)/$(Build.Repository.Name)
  underscoreName: kupaliska_starz_fe

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Github Packages'
        repository: $(dockerRepository)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
      displayName: Build Docker Image
      env:
        REACT_APP_HOST: "%{HOST}%"
        REACT_APP_RECAPTCHA_KEY: "%{RECAPTCHA_CLIENT_SECRET}%"
    - task: Docker@2
      inputs:
        containerRegistry: 'Github Packages'
        repository: $(dockerRepository)
        command: 'Push'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual')))
      displayName: Push Docker Image (not on PR)

- stage: Development
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual')))
  variables:
  - group: Kupaliska-Common-Stage
  jobs:
  - deployment: Development
    environment:
      name: Staging
      resourceType: VirtualMachine
      tags: docker
    variables:
      NAME: $(underscoreName)_stage
      PORT: 9005
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - download: none
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Github Packages'
              dockerComposeFile: 'docker-compose.yml'
              projectName: "$(underscoreName)_stage"
              action: 'Run services'
              buildImages: false
            env:
              IMAGE: docker.pkg.github.com/$(dockerRepository)
              IMAGE_TAG: $(tag)
              HOST: $(HOST)
              # Expose Secret Variables to env
              RECAPTCHA_CLIENT_SECRET: $(RECAPTCHA_CLIENT_SECRET)
- stage: Staging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  variables:
  - group: Kupaliska-Common-Prod
  jobs:
  - deployment: Staging
    environment:
      name: Production
      resourceType: VirtualMachine
      tags: docker
    variables:
      NAME: $(underscoreName)_stage
      PORT: 18001
      HOST: kupaliska-api-staging.bratislava.sk
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - download: none
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Github Packages'
              dockerComposeFile: 'docker-compose.yml'
              projectName: "$(underscoreName)_stage"
              action: 'Run services'
              buildImages: false
            env:
              IMAGE: docker.pkg.github.com/$(dockerRepository)
              IMAGE_TAG: $(tag)
              HOST: $(HOST)
              # Expose Secret Variables to env
              RECAPTCHA_CLIENT_SECRET: $(RECAPTCHA_CLIENT_SECRET)

- stage: Production
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  variables:
  - group: Kupaliska-Common-Prod
  jobs:
  - deployment: Production
    environment:
      name: Production
      resourceType: VirtualMachine
      tags: docker
    variables:
      NAME: $(underscoreName)
      PORT: 19001
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - download: none
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Github Packages'
              dockerComposeFile: 'docker-compose.yml'
              projectName: "$(underscoreName)"
              action: 'Run services'
              buildImages: false
            env:
              IMAGE: docker.pkg.github.com/$(dockerRepository)
              IMAGE_TAG: $(tag)
              HOST: $(HOST)
              # Expose Secret Variables to env
              RECAPTCHA_CLIENT_SECRET: $(RECAPTCHA_CLIENT_SECRET)