apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendertron
  labels:
    service: rendertron
  namespace: ${NAMESPACE}
  annotations:
    repositoryUrl: ${BUILD_REPOSITORY_URI}
    commit: ${COMMIT}
    tag: ${TAG}
    image: ${IMAGE}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rendertron
  template:
    metadata:
      labels:
        service: rendertron
    spec:
      containers:
        - image: dockette/rendertron
          name: rendertron
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ${IMAGE_PULL_SECRET}
