resources:
  - deployment.yml
  - service-app.yml
  - ingress.yml
  - admin.ingress.yml
  - deployment.rendertron.yml
  - service.rendertron.yml
  - secrets/app.secret.yml
configurations:
  - configuration.yml

# Keep as is
namePrefix: ${BUILD_REPOSITORY_NAME}-
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  source: ${BUILD_REPOSITORY_NAME}

commonAnnotations:
  repositoryUrl: ${BUILD_REPOSITORY_URI}

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: env
  envs:
  - .env