resources:
  - 'deployment.yml'
  - 'service-app.yml'
  - 'ingress.yml'
  - 'deployment.rendertron.yml'
  - 'service.rendertron.yml'
configurations:
  - configuration.yml

# Keep as is
namePrefix: ${BUILD_REPOSITORY_NAME}-
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  source: ${BUILD_REPOSITORY_NAME}

commonAnnotations:
  repositoryUrl: ${BUILD_REPOSITORY_URI}

configMapGenerator:
- name: env
  envs:
  - .env