apiVersion: v1
kind: Service
metadata:
  name: rendertron
  namespace: ${NAMESPACE}
  labels:
    service: rendertron
spec:
  ports:
    - protocol: TCP
      port: ${RENDERTRON_PORT}
      targetPort: ${RENDERTRON_PORT}
  selector:
    service: rendertron
