name: Strapi/Next deploy pipeline
on:
  push:
    tags:
      - 'dev**'
      - 'staging**'
      - 'prod**'
    branches:
      - master

jobs:
  conditions:
    name: Check for cluster conditions
    uses: bratislava/github-actions/.github/workflows/cluster-deploy-conditions-inhouse.yml@stable

  deploy-dev:
    name: Deploy 'kupaliska' to DEV
    if: needs.conditions.outputs.dev == 'true'
    needs: [conditions]
    uses: bratislava/github-actions/.github/workflows/deploy-with-bratiska-cli-inhouse.yml@stable
    with:
      directory: '.'
      cluster: tkg-innov-dev
      url: https://tkg.dev.bratislava.sk
      debug: --debug
      version: beta
    secrets:
      service-account: ${{ secrets.DEV_STANDALONE_TOKEN }}
      registry-pass: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}

  deploy-staging:
    name: Deploy 'kupaliska' to STAGING
    if: needs.conditions.outputs.staging == 'true'
    needs: [conditions]
    uses: bratislava/github-actions/.github/workflows/deploy-with-bratiska-cli-inhouse.yml@stable
    with:
      directory: '.'
      cluster: tkg-innov-staging
      url: https://tkg.staging.bratislava.sk
      debug: --debug
      flag: --staging
    secrets:
      service-account: ${{ secrets.STAGING_STANDALONE_TOKEN }}
      registry-pass: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}

  deploy-prod:
    name: Deploy 'kupaliska' to PROD
    if: needs.conditions.outputs.prod == 'true'
    needs: [conditions]
    uses: bratislava/github-actions/.github/workflows/deploy-with-bratiska-cli-inhouse.yml@stable
    with:
      directory: '.'
      cluster: tkg-innov-prod
      url: https://tkg.bratislava.sk
      flag: --production
      debug: --debug
    secrets:
      service-account: ${{ secrets.PROD_STANDALONE_TOKEN }}
      registry-pass: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
