name: Validate and build PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      push: false
